# Generated by Django 4.2.7 on 2025-02-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=80, verbose_name='Товар')),
                ('status', models.BooleanField(choices=[(True, 'Пришло'), (False, 'Не пришло')], default=False, verbose_name='Статус')),
                ('trek_number', models.IntegerField(unique=True, verbose_name='Трек номер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
