# Generated by Django 5.1.4 on 2024-12-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=80, verbose_name='Товар')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('trek_number', models.IntegerField(verbose_name='Трек номер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trek_number', models.IntegerField(verbose_name='Трек номер')),
            ],
        ),
    ]
